In [7]:
import pandas as pd

df = pd.read_csv("data/adult_with_headers (1).csv")

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [9]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [10]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [11]:
df.nunique()

age                  73
workclass             9
fnlwgt            21648
education            16
education_num        16
marital_status        7
occupation           15
relationship          6
race                  5
sex                   2
capital_gain        119
capital_loss         92
hours_per_week       94
native_country       42
income                2
dtype: int64

In [13]:
df_encoded = df.copy()

df_encoded.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [15]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, drop=None)

sex_encoded = encoder.fit_transform(df_encoded[["sex"]])

sex_encoded_df = pd.DataFrame(
    sex_encoded,
    columns=encoder.get_feature_names_out(["sex"]),
    index=df_encoded.index
)

sex_encoded_df.head()

   sex_ Female  sex_ Male
0          0.0        1.0
1          0.0        1.0
2          0.0        1.0
3          0.0        1.0
4          1.0        0.0

In [16]:
df_encoded = pd.concat([df_encoded, sex_encoded_df], axis=1)

df_encoded.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,sex_ Female,sex_ Male
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0.0,1.0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0.0,1.0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0.0,1.0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0.0,1.0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,1.0,0.0

In [17]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_columns = [
    "workclass",
    "education",
    "marital_status",
    "occupation",
    "relationship",
    "native_country"
]

for col in label_columns:
    df_encoded[col] = label_encoder.fit_transform(df_encoded[col])

df_encoded.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,sex_ Female,sex_ Male
0,39,7,77516,9,13,4,1,1,White,Male,2174,0,40,39,<=50K,0.0,1.0
1,50,6,83311,9,13,2,4,0,White,Male,0,0,13,39,<=50K,0.0,1.0
2,38,4,215646,11,9,0,6,1,White,Male,0,0,40,39,<=50K,0.0,1.0
3,53,4,234721,1,7,2,6,0,Black,Male,0,0,40,39,<=50K,0.0,1.0
4,28,4,338409,9,13,2,10,5,Black,Female,0,0,40,5,<=50K,1.0,0.0

In [18]:
df_encoded.dtypes

age                 int64
workclass           int64
fnlwgt              int64
education           int64
education_num       int64
marital_status      int64
occupation          int64
relationship        int64
race                  str
sex                   str
capital_gain        int64
capital_loss        int64
hours_per_week      int64
native_country      int64
income                str
sex_ Female       float64
sex_ Male         float64
dtype: object

In [19]:
from sklearn.preprocessing import LabelEncoder

# Label encode race
race_encoder = LabelEncoder()
df_encoded["race"] = race_encoder.fit_transform(df_encoded["race"])

# Encode income target
income_encoder = LabelEncoder()
df_encoded["income"] = income_encoder.fit_transform(df_encoded["income"])

# Remove original sex column because One-Hot encoded columns were created
df_encoded = df_encoded.drop(columns=["sex"])

df_encoded.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,income,sex_ Female,sex_ Male
0,39,7,77516,9,13,4,1,1,4,2174,0,40,39,0,0.0,1.0
1,50,6,83311,9,13,2,4,0,4,0,0,13,39,0,0.0,1.0
2,38,4,215646,11,9,0,6,1,4,0,0,40,39,0,0.0,1.0
3,53,4,234721,1,7,2,6,0,2,0,0,40,39,0,0.0,1.0
4,28,4,338409,9,13,2,10,5,2,0,0,40,5,0,1.0,0.0

In [20]:
df_encoded.dtypes

age                 int64
workclass           int64
fnlwgt              int64
education           int64
education_num       int64
marital_status      int64
occupation          int64
relationship        int64
race                int64
capital_gain        int64
capital_loss        int64
hours_per_week      int64
native_country      int64
income              int64
sex_ Female       float64
sex_ Male         float64
dtype: object

In [21]:
X = df_encoded.drop(columns=["income"])
y = df_encoded["income"]

X.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male
0,39,7,77516,9,13,4,1,1,4,2174,0,40,39,0.0,1.0
1,50,6,83311,9,13,2,4,0,4,0,0,13,39,0.0,1.0
2,38,4,215646,11,9,0,6,1,4,0,0,40,39,0.0,1.0
3,53,4,234721,1,7,2,6,0,2,0,0,40,39,0.0,1.0
4,28,4,338409,9,13,2,10,5,2,0,0,40,5,1.0,0.0

In [22]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

X_standard_scaled = standard_scaler.fit_transform(X)

X_standard_scaled = pd.DataFrame(
    X_standard_scaled,
    columns=X.columns,
    index=X.index
)

X_standard_scaled.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male
0,0.030671,2.150579,-1.063611,-0.335437,1.134739,0.921634,-1.317809,-0.277805,0.393668,0.148453,-0.21666,-0.035429,0.291569,-0.703071,0.703071
1,0.837109,1.463736,-1.008707,-0.335437,1.134739,-0.406212,-0.608387,-0.900181,0.393668,-0.145920,-0.21666,-2.222153,0.291569,-0.703071,0.703071
2,-0.042642,0.090050,0.245079,0.181332,-0.420060,-1.734058,-0.135438,-0.277805,0.393668,-0.145920,-0.21666,-0.035429,0.291569,-0.703071,0.703071
3,1.057047,0.090050,0.425801,-2.402511,-1.197459,-0.406212,-0.135438,-0.900181,-1.962621,-0.145920,-0.21666,-0.035429,0.291569,-0.703071,0.703071
4,-0.775768,0.090050,1.408176,-0.335437,1.134739,-0.406212,0.810458,2.211698,-1.962621,-0.145920,-0.21666,-0.035429,-4.054223,1.422331,-1.422331

In [23]:
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

X_minmax_scaled = minmax_scaler.fit_transform(X)

X_minmax_scaled = pd.DataFrame(
    X_minmax_scaled,
    columns=X.columns,
    index=X.index
)

X_minmax_scaled.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male
0,0.301370,0.875,0.044302,0.600000,0.800000,0.666667,0.071429,0.2,1.0,0.02174,0.0,0.397959,0.951220,0.0,1.0
1,0.452055,0.750,0.048238,0.600000,0.800000,0.333333,0.285714,0.0,1.0,0.00000,0.0,0.122449,0.951220,0.0,1.0
2,0.287671,0.500,0.138113,0.733333,0.533333,0.000000,0.428571,0.2,1.0,0.00000,0.0,0.397959,0.951220,0.0,1.0
3,0.493151,0.500,0.151068,0.066667,0.400000,0.333333,0.428571,0.0,0.5,0.00000,0.0,0.397959,0.951220,0.0,1.0
4,0.150685,0.500,0.221488,0.600000,0.800000,0.333333,0.714286,1.0,0.5,0.00000,0.0,0.397959,0.121951,1.0,0.0

In [24]:
X_minmax_scaled.min().min(), X_minmax_scaled.max().max()

(np.float64(0.0), np.float64(1.0))

In [25]:
df_features = df.copy()

# Feature 1: Age group
df_features["age_group"] = pd.cut(
    df_features["age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle_Aged", "Senior"]
)

# Feature 2: Capital net
df_features["capital_net"] = (
    df_features["capital_gain"] - df_features["capital_loss"]
)

df_features[["age", "age_group", "capital_gain", "capital_loss", "capital_net"]].head()

   age    age_group  capital_gain  capital_loss  capital_net
0   39        Adult          2174             0         2174
1   50  Middle_Aged             0             0            0
2   38        Adult             0             0            0
3   53  Middle_Aged             0             0            0
4   28        Adult             0             0            0

In [26]:
df_features["capital_gain"].skew()

np.float64(11.953847687699804)

In [27]:
import numpy as np

df_features["capital_gain_log"] = np.log1p(df_features["capital_gain"])

df_features[["capital_gain", "capital_gain_log"]].head()

   capital_gain  capital_gain_log
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000

In [28]:
df_features["capital_gain_log"].skew()

np.float64(3.096143524467517)

In [29]:
df_features[[
    "age",
    "age_group",
    "capital_gain",
    "capital_loss",
    "capital_net",
    "capital_gain_log"
]].head()

   age    age_group  capital_gain  capital_loss  capital_net  capital_gain_log
0   39        Adult          2174             0         2174          7.684784
1   50  Middle_Aged             0             0            0          0.000000
2   38        Adult             0             0            0          0.000000
3   53  Middle_Aged             0             0            0          0.000000
4   28        Adult             0             0            0          0.000000

In [30]:
df_features.shape

(32561, 18)

In [31]:
df_features.isnull().sum().sum()

np.int64(0)